export const SELECTED_PRODUCTS_LIST = [{
    id: 1,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'MAc\'s original, BBQ & Salt & Pepper',
    subTitle: '$4.10',
    price: 4.10,
    qty: 1,
}, {
    id: 2,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
}, {
    id: 3,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'MAc\'s original, BBQ & Salt & Pepper',
    subTitle: '$4.10',
    price: 4.10,
    qty: 1,
}, {
    id: 4,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
}, {
    id: 5,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
}, {
    id: 6,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'MAc\'s original, BBQ & Salt & Pepper',
    subTitle: '$4.10',
    price: 4.10,
    qty: 1,
}, {
    id: 7,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
},
{
    id: 8,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
}, {
    id: 9,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'MAc\'s original, BBQ & Salt & Pepper',
    subTitle: '$4.10',
    price: 4.10,
    qty: 1,
}, {
    id: 10,
    imageUrl: require('../../../assets/images/products/small/kurkure.webp'),
    title: 'Great Value Cocoa Roasted Almonds',
    subTitle: '$10.50',
    price: 10.50,
    qty: 2,
}]